#!/bin/bash
#
#This is a shell script which is used for create user

user_create ()                                                                           
{
echo "**************** creation of userstarted **********************"
read -p "enter the user name :" username
read -p "enter the passwod :" password
sudo useradd -m "$username"
echo -e "$password\n$password" | sudo passwd "$username"
echo "**************** user creation completed *********************"
}
user_create
user_create


## ## User_create is the function we wrap the whole script in a function. now how many time we call the function we will create an user.
