#!/bin/bash
#
#This is a shell script which is used for create user and then delete the user also


echo "**************** creation of userstarted **********************"
read -p "enter the user name :" username
read -p "enter the passwod :" password
sudo useradd -m "$username"
echo -e "$password\n$password" | sudo passwd "$username"
echo "**************** user creation completed *********************"
sudo userdel "$username"
echo "user deleted"
cat /etc/passwd | grep "$username" | wc
echo "if the wc is 0 then user deletede"

