#!/bin/bash
#
#This is a shell script which is used for create user


echo "**************** creation of userstarted **********************"
read -p "enter the user name :" username
read -p "enter the passwod :" password
sudo useradd -m "$username"
sudo passwd "$username"
echo "**************** user creation completed *********************"


